Created a phpbeautifyrc.json file - Solution to issue #2
OSS-Enthusiasts/brackets-php-beautify pull request #3
Opened 2020-05-03 07:34 UTC by Shankhanil

Here are the details of the changes that I have made. 

1. I have created the phpbeautifyrc.json file. I have given default value to the parameters
2. I have inserted a small code piece in /*...*/ comments. The code piece is supposed to read the phpbeautifyrc.json and get the parameters for formatting. But, in my environment it is malfunctioning. I would like _you_ to review it, and suggest the changes. 
3. I would also need to modify the .replace(...) statements in format() in php.js file, and include conditional replacements based on the parameters in .json file. But this could be done only _after the issue in point 2 is resolved_.

2020-05-03 13:07 UTC, nadchif commented
@Shankhanil Thank you once again! I've reviewed it an added a suggested implementation. Check it out and tell me what you think

2020-05-03 13:11 UTC, nadchif requested changes
Please checkout the suggested implementation and tell me what you think

2020-05-04 09:19 UTC, Shankhanil commented
hey @nadchif Great piece of code on your side!. But, I am git push-ing my changes, but they aren't showing up here. 

Also, send me tutorials on how to read preferences from a promise object.

2020-05-04 09:26 UTC, Shankhanil reviewed
I have accepted and included the changes in the code. Thanks for the contribution.

2020-05-04 09:30 UTC, nadchif commented on src/thirdparty/php.js
> +
I already did the piece of code to read the preferences and handle the promises logic. The variable `customConfiguratuon` already loads the preferences. You could use that variable.

To test it, open a folder (project) in brackets that contains a `.phpbeautifyrc.json`, you will see the setting will be loaded and logged into the console by line 68

2020-05-04 10:01 UTC, Shankhanil commented
then the PR is ready to be merged.

2020-05-04 13:52 UTC, merged

2020-05-04 13:53 UTC, nadchif commented
I've merged the PR into the development branch. We will merge into the master when the implementation is complete and ready for new version release

2020-05-04 14:00 UTC, nadchif commented
Please check proceed with the implementation. See line 56 of [src/thirdparty/php.js](https://github.com/nadchif/brackets-php-beautify/blob/development/src/thirdparty/php.js) on the [development](https://github.com/nadchif/brackets-php-beautify/blob/development/src/thirdparty/php.js) branch

2020-05-04 15:57 UTC, Shankhanil commented
I will look into it ASAP!